export { default as Home } from './Home'
export { default as Account } from './Account'
export { default as About } from './About'
export { default as Patients } from './Patients'
export { default as Schedule } from './Schedule'
export { default as NewCases } from './NewCases'